"""
Mesh + skin generator for THE OBSERVER.

Builds one organic mesh per rig segment (same names and sizes as the parts in
src/shared/ObserverRig.luau), each in that part's local space (Y up, front -Z),
plus a seamless PBR skin (colour / normal / roughness).

Outputs:
    assets/observer/<Segment>.obj
    assets/observer/observer_skin_{color,normal,roughness}.png
    src/shared/Config/ObserverMeshMeta.luau   (bounding box of every mesh, so the
                                                game places and sizes them exactly)

Usage:
    python3 tools/gen_observer.py
"""

import math
import os
import sys

import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(__file__))
import gen_textures as tex  # noqa: E402  (noise helpers)

ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "assets", "observer")
META = os.path.join(ROOT, "src", "shared", "Config", "ObserverMeshMeta.luau")


# ---------------------------------------------------------------------------
# mesh building
# ---------------------------------------------------------------------------

class Mesh:
    def __init__(self):
        self.v = []
        self.uv = []
        self.f = []  # triangles of vertex indices (uv shares the index)

    def add_grid(self, pts, uvs, closed_u=True):
        """pts/uvs: rings x columns (columns include the duplicated seam column)."""
        base = len(self.v)
        rows, cols = len(pts), len(pts[0])
        for r in range(rows):
            for c in range(cols):
                self.v.append(pts[r][c])
                self.uv.append(uvs[r][c])
        for r in range(rows - 1):
            for c in range(cols - 1):
                a = base + r * cols + c
                b = a + 1
                d = a + cols
                e = d + 1
                self.f.append((a, d, b))
                self.f.append((b, d, e))

    def merge(self, other):
        base = len(self.v)
        self.v += other.v
        self.uv += other.uv
        self.f += [(a + base, b + base, c + base) for a, b, c in other.f]

    def flip(self):
        self.f = [(a, c, b) for a, b, c in self.f]

    def bbox(self):
        arr = np.array(self.v)
        return arr.min(axis=0), arr.max(axis=0)

    def write_obj(self, path):
        v = np.array(self.v)
        n = np.zeros_like(v)
        for a, b, c in self.f:
            fn = np.cross(v[b] - v[a], v[c] - v[a])
            n[a] += fn
            n[b] += fn
            n[c] += fn
        n /= np.maximum(np.linalg.norm(n, axis=1, keepdims=True), 1e-9)
        with open(path, "w") as fh:
            fh.write("# THE OBSERVER - generated by tools/gen_observer.py\n")
            fh.write("o %s\n" % os.path.splitext(os.path.basename(path))[0])
            for p in v:
                fh.write("v %.5f %.5f %.5f\n" % tuple(p))
            for t in self.uv:
                fh.write("vt %.5f %.5f\n" % tuple(t))
            for q in n:
                fh.write("vn %.5f %.5f %.5f\n" % tuple(q))
            for a, b, c in self.f:
                fh.write("f %d/%d/%d %d/%d/%d %d/%d/%d\n" % (a + 1, a + 1, a + 1, b + 1, b + 1, b + 1, c + 1, c + 1, c + 1))
        return len(self.f)


def frames(path):
    """Parallel-transport frames along a polyline: tangent, normal, binormal."""
    path = np.array(path, dtype=float)
    t = np.gradient(path, axis=0)
    t /= np.linalg.norm(t, axis=1, keepdims=True)
    up = np.array([0.0, 0.0, -1.0]) if abs(t[0][2]) < 0.9 else np.array([1.0, 0.0, 0.0])
    nrm = np.cross(t[0], up)
    nrm /= np.linalg.norm(nrm)
    ns, bs = [], []
    for i in range(len(path)):
        if i > 0:
            v = np.cross(t[i - 1], t[i])
            s = np.linalg.norm(v)
            if s > 1e-8:
                ang = math.asin(min(1.0, s))
                v /= s
                nrm = nrm * math.cos(ang) + np.cross(v, nrm) * math.sin(ang) + v * np.dot(v, nrm) * (1 - math.cos(ang))
        b = np.cross(t[i], nrm)
        ns.append(nrm / np.linalg.norm(nrm))
        bs.append(b / np.linalg.norm(b))
    return path, ns, bs


def tube(path, rx, rz, segs=24, mod=None, cap0=True, cap1=True, uv_scale=2.0):
    """Loft an elliptical tube along `path` (list of points). rx/rz/mod are
    functions of t in 0..1 (and theta for mod). Rounded caps at both ends."""
    p, ns, bs = frames(path)
    count = len(p)
    lengths = np.concatenate([[0], np.cumsum(np.linalg.norm(np.diff(p, axis=0), axis=1))])
    total = lengths[-1]
    rows = []
    uvs = []
    circumference = 2 * math.pi * (rx(0.5) + rz(0.5)) / 2
    urep = max(1, round(circumference / uv_scale))

    def ring(center, nrm, bin_, sx, sz, t, v):
        row, uvrow = [], []
        for c in range(segs + 1):
            th = 2 * math.pi * c / segs
            m = mod(t, th) if mod else 1.0
            pt = center + nrm * math.cos(th) * sx * m + bin_ * math.sin(th) * sz * m
            row.append(pt)
            uvrow.append((c / segs * urep, v))
        return row, uvrow

    if cap0:
        r0 = (rx(0) + rz(0)) / 2
        for k in range(4, 0, -1):
            a = k / 4 * (math.pi / 2)
            f = math.cos(a)
            off = -math.sin(a) * r0 * 0.8
            tang = (p[1] - p[0]) / max(np.linalg.norm(p[1] - p[0]), 1e-9)
            row, uvrow = ring(p[0] + tang * off, ns[0], bs[0], max(rx(0) * f, 1e-3), max(rz(0) * f, 1e-3), 0.0, off / uv_scale)
            rows.append(row)
            uvs.append(uvrow)
    for i in range(count):
        t = lengths[i] / total if total > 0 else 0
        row, uvrow = ring(p[i], ns[i], bs[i], rx(t), rz(t), t, lengths[i] / uv_scale)
        rows.append(row)
        uvs.append(uvrow)
    if cap1:
        r1 = (rx(1) + rz(1)) / 2
        tang = (p[-1] - p[-2]) / max(np.linalg.norm(p[-1] - p[-2]), 1e-9)
        for k in range(1, 5):
            a = k / 4 * (math.pi / 2)
            f = math.cos(a)
            off = math.sin(a) * r1 * 0.8
            row, uvrow = ring(p[-1] + tang * off, ns[-1], bs[-1], max(rx(1) * f, 1e-3), max(rz(1) * f, 1e-3), 1.0, (total + off) / uv_scale)
            rows.append(row)
            uvs.append(uvrow)
    m = Mesh()
    m.add_grid(rows, uvs)
    return m


def line(a, b, n):
    a, b = np.array(a, float), np.array(b, float)
    return [a + (b - a) * (i / (n - 1)) for i in range(n)]


def bump(x, center, width):
    return math.exp(-((x - center) / width) ** 2)


def angdist(a, b):
    d = (a - b + math.pi) % (2 * math.pi) - math.pi
    return abs(d)


# theta convention for vertical tubes (up or down): frames() starts the
# binormal on +Z, so theta = pi/2 points at the BACK (+Z) and 3pi/2 at the
# FRONT (-Z, the way the Observer faces).
FRONT, BACK = 3 * math.pi / 2, math.pi / 2


def profile(points):
    """Smooth radius profile through (t, r) control points."""
    ts = np.array([q[0] for q in points])
    rs = np.array([q[1] for q in points])

    def f(t):
        t = min(1.0, max(0.0, t))
        # cosine-eased interpolation between neighbouring control points
        k = int(np.searchsorted(ts, t, side="right")) - 1
        k = max(0, min(len(ts) - 2, k))
        a = (t - ts[k]) / max(ts[k + 1] - ts[k], 1e-9)
        a = 0.5 - 0.5 * math.cos(a * math.pi)
        return rs[k] * (1 - a) + rs[k + 1] * a

    return f


def upper_torso():
    # box 1.55 x 2.3 x 0.62. Gaunt: pinched waist, ribcage, then bony shoulders
    # wide enough to meet the arms (shoulder joints at x = +-0.95)
    rx = profile([(0, 0.3), (0.18, 0.34), (0.45, 0.5), (0.62, 0.56), (0.8, 0.66), (0.9, 0.86), (0.96, 0.7), (1.0, 0.24)])
    rz = profile([(0, 0.19), (0.18, 0.2), (0.5, 0.3), (0.7, 0.31), (0.88, 0.25), (1.0, 0.16)])

    def mod(t, th):
        m = 1.0
        front = bump(angdist(th, FRONT), 0, 1.0)
        side = bump(angdist(th, FRONT), 1.2, 0.5)
        # ribs: sharp ridges across chest and flanks between t 0.35 and 0.82
        if 0.3 < t < 0.85:
            ridge = max(0.0, math.sin((t - 0.3) * 13 * math.pi)) ** 4
            m += 0.09 * (front + 0.7 * side) * ridge * bump(t, 0.6, 0.25)
        # sunken belly under the ribs, a sternum line between them
        m -= 0.2 * front * bump(t, 0.2, 0.12)
        m += 0.04 * bump(angdist(th, FRONT), 0, 0.08) * bump(t, 0.65, 0.18)
        # spine: vertebrae down the back, with a groove either side
        back = bump(angdist(th, BACK), 0, 0.13)
        m += 0.16 * back * (0.5 + 0.5 * max(0.0, math.sin(t * 24 * math.pi)))
        m -= 0.06 * bump(angdist(th, BACK), 0.32, 0.12)
        # shoulder blades jutting out
        for sgn in (-1, 1):
            m += 0.16 * bump(angdist(th, BACK + sgn * 0.7), 0, 0.28) * bump(t, 0.78, 0.1)
        # collarbones and a hollow above them
        m += 0.08 * front * bump(t, 0.9, 0.025)
        m -= 0.06 * front * bump(t, 0.95, 0.02)
        return m

    return tube(line((0, -1.25, 0), (0, 1.25, 0), 80), rx, rz, segs=56, mod=mod)


def lower_torso():
    rx = profile([(0, 0.3), (0.35, 0.44), (0.65, 0.42), (1.0, 0.3)])
    rz = profile([(0, 0.18), (0.5, 0.22), (1.0, 0.18)])

    def mod(t, th):
        m = 1.0
        for sgn in (-1, 1):
            m += 0.16 * bump(angdist(th, FRONT + sgn * 0.95), 0, 0.22) * bump(t, 0.6, 0.15)  # hip bones
        m -= 0.1 * bump(angdist(th, FRONT), 0, 0.45) * bump(t, 0.75, 0.2)
        m += 0.12 * bump(angdist(th, BACK), 0, 0.12)
        return m

    return tube(line((0, -0.42, 0), (0, 0.48, 0), 18), rx, rz, segs=40, mod=mod)


def neck():
    def mod(t, th):
        m = 1.0
        for side in (-1, 1):
            m += 0.22 * bump(angdist(th, FRONT + side * 0.6), 0, 0.22)  # tendons
        m += 0.12 * bump(angdist(th, FRONT), 0, 0.2) * bump(t, 0.45, 0.12)  # throat knot
        return m

    return tube(line((0, -0.62, 0), (0, 0.62, 0), 20), lambda t: 0.12 - 0.02 * t, lambda t: 0.13 - 0.02 * t, segs=24, mod=mod)


HEAD_FACE_DEPTH = 0.09


_HEAD_RX = None
_HEAD_RZ = None


def head_profile(t):
    # t 0 = chin, 1 = crown: a narrow pointed jaw, long cranium swept back
    global _HEAD_RX, _HEAD_RZ
    if _HEAD_RX is None:
        _HEAD_RX = profile([(0, 0.08), (0.2, 0.24), (0.45, 0.33), (0.7, 0.41), (0.88, 0.38), (1.0, 0.3)])
        _HEAD_RZ = profile([(0, 0.16), (0.25, 0.33), (0.55, 0.42), (0.8, 0.47), (0.95, 0.42), (1.0, 0.34)])
    return _HEAD_RX(t), _HEAD_RZ(t)


def head():
    def mod(t, th):
        m = 1.0
        # the face is a shallow recess: the two face plates sit in it
        face = bump(angdist(th, FRONT), 0, 0.55) * bump(t, 0.5, 0.32)
        m -= HEAD_FACE_DEPTH * 2 * face
        # cranium swells at the back, cheekbones under the plates
        m += 0.08 * bump(angdist(th, BACK), 0, 0.9) * bump(t, 0.75, 0.25)
        for side in (-1, 1):
            m += 0.06 * bump(angdist(th, FRONT + side * 1.0), 0, 0.22) * bump(t, 0.42, 0.1)  # cheekbones
            m -= 0.08 * bump(angdist(th, FRONT + side * 1.45), 0, 0.3) * bump(t, 0.66, 0.1)  # sunken temples
        return m

    # the crown leans back over the neck
    return tube([np.array([0, -0.66 + 1.32 * i / 47, 0.02 + 0.16 * (i / 47) ** 2]) for i in range(48)], lambda t: head_profile(t)[0], lambda t: head_profile(t)[1], segs=40, mod=mod)


def face_half(side):
    """A curved plate covering one half of the face recess, in the FaceL/FaceR
    part's local space (part centre at head-local (side*0.21, -0.05, -0.475))."""
    center = np.array([side * 0.21, -0.05, -0.475])
    rows_out, rows_in, uvs = [], [], []
    ny, nx = 22, 10
    for j in range(ny):
        y = -0.55 + 1.1 * j / (ny - 1)
        t = (y + 0.66) / 1.32
        rx, rz = head_profile(t)
        row_o, row_i, uvrow = [], [], []
        for i in range(nx):
            u = i / (nx - 1)
            x = side * (0.012 + u * (rx * 0.82 - 0.012))
            # follow the head's front surface
            zf = -rz * math.sqrt(max(0.0, 1 - (x / max(rx, 1e-3)) ** 2)) * 0.98
            p = np.array([x, y, zf]) - center
            # brow ridge and a faint cheek hollow make it read as a face
            p[2] -= 0.025 * bump(y, 0.18, 0.06) - 0.02 * bump(y, -0.12, 0.08) * u
            row_o.append(p)
            row_i.append(p + np.array([0, 0, 0.035]))
            uvrow.append((u * 0.5, (y + 0.6) * 0.5))
        rows_out.append(row_o)
        rows_in.append(row_i)
        uvs.append(uvrow)
    outer = Mesh()
    outer.add_grid(rows_out, uvs, closed_u=False)
    if side > 0:
        outer.flip()
    inner = Mesh()
    inner.add_grid(rows_in, uvs, closed_u=False)
    if side < 0:
        inner.flip()
    outer.merge(inner)
    return outer


def limb(length, r_top, r_bottom, knob_top=0.0, knob_bottom=0.0, ridges=0.0, segs=20):
    half = length / 2

    def rx(t):
        r = r_top + (r_bottom - r_top) * t
        r *= 1 + knob_bottom * bump(t, 0.95, 0.07) + knob_top * bump(t, 0.05, 0.07)
        # wasted muscle: a thin middle
        return r * (1 - 0.12 * bump(t, 0.5, 0.25))

    def mod(t, th):
        m = 1.0
        if ridges:
            m += ridges * bump(angdist(th, FRONT), 0, 0.25)  # shin / bone ridge
            m += ridges * 0.6 * bump(angdist(th, BACK + 0.5), 0, 0.3) * bump(t, 0.3, 0.2)
        return m

    # built top (t=0) to bottom (t=1), overlapping the joints a little
    return tube(line((0, half + 0.08, 0), (0, -half - 0.08, 0), 34), rx, rx, segs=segs, mod=mod)


def hand():
    """Palm plus three long two-jointed fingers hanging down (matches the rig's
    finger parts so those can be hidden)."""
    m = tube(line((0, 0.28, 0), (0, -0.26, 0), 10), lambda t: 0.16 - 0.02 * t, lambda t: 0.06, segs=20,
             mod=lambda t, th: 1 + 0.08 * bump(t, 0.95, 0.08))
    for f in (-1, 0, 1):
        x0 = f * 0.1
        a1 = math.radians(f * 5)
        p0 = np.array([x0, -0.22, 0.0])
        d1 = np.array([math.sin(a1), -math.cos(a1), -0.06])
        d1 /= np.linalg.norm(d1)
        k1 = p0 + d1 * 0.78
        d2 = np.array([d1[0], d1[1] * math.cos(math.radians(14)), -math.sin(math.radians(14)) * 1.3])
        d2 /= np.linalg.norm(d2)
        tip = k1 + d2 * 0.62
        path = line(p0, k1, 10) + line(k1, tip, 9)[1:]

        def rx(t):
            return (0.042 - 0.018 * t) * (1 + 0.35 * bump(t, 0.56, 0.05) + 0.2 * bump(t, 0.04, 0.05))

        m.merge(tube(path, rx, rx, segs=10))
    return m


def foot():
    def rx(t):
        return 0.17 * (0.6 + 0.4 * math.sin(min(1, t * 1.4) * math.pi * 0.5)) * (1 - 0.3 * t)

    def rz(t):
        return 0.11 * (1 - 0.55 * t)

    def mod(t, th):
        # long toes: ridges along the top front
        return 1 + 0.1 * bump(t, 0.85, 0.15) * (0.5 + 0.5 * math.cos(th * 3))

    # along -Z (forward), slightly arched; heel at the back
    path = [np.array([0, -0.02 + 0.04 * math.sin(i / 19 * math.pi), 0.52 - 1.12 * i / 19]) for i in range(20)]
    return tube(path, rx, rz, segs=20, mod=mod)


SEGMENTS = {
    "UpperTorso": upper_torso,
    "LowerTorso": lower_torso,
    "Neck": neck,
    "Head": head,
    "FaceL": lambda: face_half(-1),
    "FaceR": lambda: face_half(1),
    "UpperArm": lambda: limb(2.5, 0.14, 0.11, knob_top=0.45, knob_bottom=0.35),
    "LowerArm": lambda: limb(2.5, 0.12, 0.07, knob_top=0.25, ridges=0.12, segs=18),
    "Hand": hand,
    "UpperLeg": lambda: limb(2.35, 0.18, 0.13, knob_bottom=0.3),
    "LowerLeg": lambda: limb(2.15, 0.13, 0.07, knob_top=0.25, ridges=0.15, segs=18),
    "Foot": foot,
}


# ---------------------------------------------------------------------------
# skin
# ---------------------------------------------------------------------------

def skin(n=1024):
    """Ash-dark skin: mottled, grey veins raised under the surface, fine
    wrinkles, a wet sheen that varies (roughness low where it glistens)."""
    mottle = tex.spectral(n, 2.4, 201)
    fine = tex.spectral(n, 0.9, 202)
    veins_raw = tex.band(n, 5, 14, 203) - 0.5
    veins = np.exp(-(veins_raw / 0.012) ** 2) * tex.smoothstep(0.4, 0.7, tex.spectral(n, 2.0, 204))
    capill = np.exp(-((tex.band(n, 20, 45, 205) - 0.5) / 0.008) ** 2) * 0.5
    wrinkles = tex.band(n, 60, 140, 206)
    wet = tex.smoothstep(0.45, 0.85, tex.spectral(n, 2.2, 207))
    pale = tex.smoothstep(0.7, 0.9, tex.spectral(n, 2.6, 208))
    base = tex.rgb(26, 25, 27) * np.ones((n, n, 1))
    col = base * (0.75 + 0.35 * mottle + 0.1 * fine)[..., None]
    col = tex.mix(col, tex.rgb(64, 66, 74), np.clip(veins * 0.8 + capill * 0.4, 0, 1))
    col = tex.mix(col, tex.rgb(70, 66, 64), pale * 0.35)
    h = fine * 0.3 + wrinkles * 0.25 + veins * 0.6 + capill * 0.2 + mottle * 0.2
    rough = 0.55 - wet * 0.35 + 0.1 * wrinkles
    os.makedirs(OUT, exist_ok=True)
    Image.fromarray((np.clip(col, 0, 1) * 255).astype(np.uint8), "RGB").save(os.path.join(OUT, "observer_skin_color.png"), optimize=True)
    nm = tex.normal_from_height(h, 3.0)
    Image.fromarray((np.clip(nm, 0, 1) * 255).astype(np.uint8), "RGB").save(os.path.join(OUT, "observer_skin_normal.png"), optimize=True)
    Image.fromarray((np.clip(rough, 0, 1) * 255).astype(np.uint8), "L").save(os.path.join(OUT, "observer_skin_roughness.png"), optimize=True)
    print("wrote observer skin")


def main():
    os.makedirs(OUT, exist_ok=True)
    meta = []
    for name, build in SEGMENTS.items():
        mesh = build()
        tris = mesh.write_obj(os.path.join(OUT, name + ".obj"))
        lo, hi = mesh.bbox()
        size = hi - lo
        center = (hi + lo) / 2
        meta.append((name, size, center))
        print("%-11s %5d tris  size %.2f %.2f %.2f" % (name, tris, size[0], size[1], size[2]))
    skin()
    with open(META, "w") as fh:
        fh.write("--[[\n\tObserverMeshMeta (generated by tools/gen_observer.py - do not edit)\n")
        fh.write("\tBounding box of every Observer mesh in its rig part's local space: the\n")
        fh.write("\tgame sizes each MeshPart to `size` and places it at `offset` from the part.\n]]\n\n")
        fh.write("return {\n")
        for name, size, center in meta:
            fh.write("\t%s = { size = Vector3.new(%.4f, %.4f, %.4f), offset = Vector3.new(%.4f, %.4f, %.4f) },\n" % (name, size[0], size[1], size[2], center[0], center[1], center[2]))
        fh.write("}\n")
    print("wrote", os.path.relpath(META, ROOT))


if __name__ == "__main__":
    main()
